### ISSUE TITLE
pauseAt example

### ISSUE THREAD

**Issue by coldes** [quangdaon/jquery-ticker#2]
Could you give an example of how to implement this - ie what the markup would be - thank you
`pauseAt: '',`

**Comment by coldes** [comment]
...seriously, not a hard question  - no response to date - so why bother having a github page?

**Comment by quangdaon** [comment]
Hey, sorry I must have accidentally disabled notifications, so I was not aware of this issue. The `pauseAt` option takes a string, which you can either set it to `track` or `item`. If set to `track`, it will pause each time it reaches the beginning of the track again, for _x_ milliseconds, where _x_ is the number set in the `delay` option. The same is true for `item`, except instead of pausing once it has cycled through the whole track, it will pause for each individual item on the ticker. Hope that clears things up.
